#!/bin/bash

rm -f model.c
rm -f $2

echo "Creating model.c file from $1 ..."
mod $1

shopt -s extglob

if test $2; 
 then target=$2;
 else target=mcsim.${1%.mod?('el')};
fi;

if test -f model.c; then \

	echo; \
	echo "Compiling and linking model ..."; \
	gcc -O3 -I/usr/local/include -L/usr/local/lib  -g -O2  model.c -lmcsim -o $target -lm  -Wall; \

fi;

if test -f $target; then \

	echo "Cleaning up ..."; \
	rm -f model.c; \

	echo "Created executable $target"; \
	echo; \

fi;
